// src/editor/MonacoEditor.vue
<script setup lang="ts">
import Monaco from '../monaco/Monaco.vue'
import type { EditorEmits, EditorProps } from '../types'

defineProps<EditorProps>()
const emit = defineEmits<EditorEmits>()

defineOptions({
  editorType: 'monaco',
})

const onChange = (code: string) => {
  emit('change', code)
}
</script>

<template>
  <Monaco
    :filename="filename"
    :value="value"
    :readonly="readonly"
    @change="onChange"
  />
</template>

// src/editor/MonacoEditor.tsx
import Monaco from '../monaco/Monaco'
import type { EditorProps } from '../types'

export default defineVaporComponent(
  ({ filename, value, readonly, onChange }: EditorProps) => {
    const change = (code: string) => {
      onChange?.(code)
    }

    return (
      <Monaco
        filename={filename}
        readonly={readonly}
        value={value}
        onChange={change}
      />
    )
  },
)
