// src/presets/vue-jsx-vapor/app.tsx
import { ref, shallowRef as useRef } from 'vue'

export default () => {
  const count = ref(0)

  const buttonRef = useRef()
  setTimeout(() => {
    buttonRef.value.click()
  }, 1000)

  return (
    <>
      <button onClick={() => count.value++} ref={buttonRef}>
        +
      </button>
      <button onClick={() => count.value--}>-</button>

      <div>{count.value}</div>
    </>
  )
}

// src/presets/react/app.tsx
import { useState, useRef, useEffect } from 'react'

export default () => {
  const [count, setCount] = useState(0)

  const buttonRef = useRef(null)
  useEffect(() => {
    setTimeout(() => {
      buttonRef.current && buttonRef.current.click()
    }, 1000)
  }, [])

  return (
    <>
      <button onClick={() => setCount(count + 1)} ref={buttonRef}>
        +
      </button>
      <button onClick={() => setCount(count - 1)}>-</button>

      <div v-if={count === 0}>eq {count}</div>
      <div v-else-if={count > 0}>lg {count}</div>
      <div v-else>lt {count}</div>
    </>
  )
}
