// src/presets/vue-jsx/welcome.tsx
import { defineComponent, ref, shallowRef as useRef } from 'vue'

export default defineComponent(() => {
  const count = ref(0)

  const buttonRef = useRef(null)
  setTimeout(() => {
    buttonRef.value && buttonRef.value.click()
  }, 1000)

  return () => (
    <>
      <button onClick={() => count.value++} ref={buttonRef}>
        +
      </button>
      <button onClick={() => count.value--}>-</button>

      <div v-if={count.value === 0}>eq {count.value}</div>
      <div v-else-if={count.value > 0}>lg {count.value}</div>
      <div v-else>lt {count.value}</div>
    </>
  )
})

// src/presets/solid/welcome.tsx
import { createSignal } from 'solid-js'

const useRef = <T,>(value: T) => value

export default () => {
  const [count, setCount] = createSignal(0)

  let buttonRef = useRef(null)
  setTimeout(() => {
    buttonRef && buttonRef.click()
  }, 1000)

  return (
    <>
      <button onClick={() => setCount(count() + 1)} ref={buttonRef}>
        +
      </button>
      <button onClick={() => setCount(count() - 1)}>-</button>

      <div v-if={count() === 0}>eq {count()}</div>
      <div v-else-if={count() > 0}>lg {count()}</div>
      <div v-else>lt {count()}</div>
    </>
  )
}
